# render.yaml
services:
  - type: worker
    name: komment-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8997883874:AAG1H8eF-b2y47kXV82uxwtlzQ_zrSxgzE8
      - key: PYTHON_VERSION
        value: 3.11.0