# render.yaml — Web Service (бесплатный)
services:
  - type: web
    name: komment-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn bot:fastapi_app --host 0.0.0.0 --port $PORT
    envVars:
      - key: BOT_TOKEN
        value: 8997883874:AAG1H8eF-b2y47kXV82uxwtlzQ_zrSxgzE8